### ISSUE TITLE
Centering tiles at MAP location makes procedure not Bayesian

### ISSUE THREAD

**Issue by ismael-mendoza** [prob-ml/bliss#387] opened 2021-12-14 02:59 UTC
As discussed during the last meeting, we should think about centering at samples from the variational distribution of location at each tile predicted from the encoder. 

Currently not such a big deal since the current master branch galaxy autoencoder makes the procedure not Bayesian anyway. Maybe rethink after #339 is merged.

**Comment by jeff-regier** [comment] 2021-12-16 14:43
Technically it's still a Bayesian procedure if you're using a MAP estimate for some latent variables---we're just not able to report the uncertainty. I agree though, we should switch to using samples from the variational distribution.

**Comment by jeff-regier** [comment] 2022-02-16 20:33
Duplicate of #363

**Closed by jeff-regier** 2022-02-16 20:33 UTC
